name: Baseline Model
description: Control experiment with default parameters

hyperparameters:
  learning_rate: 0.001
  batch_size: 32
  epochs: 100
  dropout: 0.2

architecture:
  layers: 4
  hidden_units: 256
  activation: relu

results:
  accuracy: 0.923
  loss: 0.187
  f1_score: 0.918
